### ISSUE TITLE
control_test_suite.nim compilation error

### ISSUE THREAD

**Issue by matkuki** [planetis-m/naygui#13]
Hi,

Specs:
- Windows 10: x64
- Nim: a little behind devel
- naygui: fresh nimble install

Compiling with `nim c control_test_suite` throws:
```
E:\Nim\naylib\test\controls_test_suite.nim(146, 41) Error: type mismatch
Expression: guiGetStyle(Default, int32(BackgroundColor))
  [1] Default: GuiControl
  [2] int32(BackgroundColor): int32

Expected one of (first mismatch at [position]):
[2] proc guiGetStyle[P: GuiStyleProperty](control: GuiControl; property: P): int32
```
Also tried the `examples/scroll_panel.nim` and that one works.

**Comment by planetis-m** [comment]
Remove the int32 type conversion. Your file must be outdated.
